// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer Menu → Menu Item*
 */
export interface FooterMenuDocumentDataMenuItemItem {
  /**
   * Title field in *Footer Menu → Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Footer Menu → Menu Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer Menu documents
 */
interface FooterMenuDocumentData {
  /**
   * Menu Item field in *Footer Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_item: prismic.GroupField<Simplify<FooterMenuDocumentDataMenuItemItem>>;

  /**
   * Facebook Link field in *Footer Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram Link field in *Footer Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Copyright field in *Footer Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Footer Menu document from Prismic
 *
 * - **API ID**: `footer_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterMenuDocumentData>,
    "footer_menu",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | BeforeAndAfterSlice
  | HeroSectionSlice
  | SimpleTextSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Site Navigation → Menu Item*
 */
export interface SiteNavigationDocumentDataMenuItemItem {
  /**
   * Title field in *Site Navigation → Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Site Navigation → Menu Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Site Navigation → CTA Item*
 */
export interface SiteNavigationDocumentDataCtaItemItem {
  /**
   * Title field in *Site Navigation → CTA Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Site Navigation → CTA Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Site Navigation documents
 */
interface SiteNavigationDocumentData {
  /**
   * Menu Item field in *Site Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_item: prismic.GroupField<
    Simplify<SiteNavigationDocumentDataMenuItemItem>
  >;

  /**
   * CTA Item field in *Site Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta_item: prismic.GroupField<Simplify<SiteNavigationDocumentDataCtaItemItem>>;

  /**
   * Logo field in *Site Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Site Navigation document from Prismic
 *
 * - **API ID**: `site_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteNavigationDocumentData>,
    "site_navigation",
    Lang
  >;

export type AllDocumentTypes =
  | FooterMenuDocument
  | HomePageDocument
  | SiteNavigationDocument;

/**
 * Primary content in *BeforeAndAfter → Default → Primary*
 */
export interface BeforeAndAfterSliceDefaultPrimary {
  /**
   * Before field in *BeforeAndAfter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: before_and_after.default.primary.before
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  before: prismic.ImageField<never>;

  /**
   * After field in *BeforeAndAfter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: before_and_after.default.primary.after
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  after: prismic.ImageField<never>;
}

/**
 * Default variation for BeforeAndAfter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BeforeAndAfterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BeforeAndAfterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BeforeAndAfter*
 */
type BeforeAndAfterSliceVariation = BeforeAndAfterSliceDefault;

/**
 * BeforeAndAfter Shared Slice
 *
 * - **API ID**: `before_and_after`
 * - **Description**: BeforeAndAfter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BeforeAndAfterSlice = prismic.SharedSlice<
  "before_and_after",
  BeforeAndAfterSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Primary CTA Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primary_cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_cta_title: prismic.KeyTextField;

  /**
   * Primary CTA URL field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primary_cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.secondary_cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_cta_title: prismic.KeyTextField;

  /**
   * Secondary CTA URL field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.secondary_cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Logo field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *SimpleText → Default → Primary*
 */
export interface SimpleTextSliceDefaultPrimary {
  /**
   * Title field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Background field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: simple_text.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;
}

/**
 * Primary content in *SimpleText → Items*
 */
export interface SimpleTextSliceDefaultItem {
  /**
   * CTA Title field in *SimpleText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.items[].cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA URL field in *SimpleText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.items[].cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SimpleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTextSliceDefaultPrimary>,
  Simplify<SimpleTextSliceDefaultItem>
>;

/**
 * Primary content in *SimpleText → Centered → Primary*
 */
export interface SimpleTextSliceCenteredPrimary {
  /**
   * Title field in *SimpleText → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.centered.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *SimpleText → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.centered.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Background field in *SimpleText → Centered → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: simple_text.centered.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;
}

/**
 * Primary content in *SimpleText → Items*
 */
export interface SimpleTextSliceCenteredItem {
  /**
   * CTA Title field in *SimpleText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.items[].cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA URL field in *SimpleText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.items[].cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Centered variation for SimpleText Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<SimpleTextSliceCenteredPrimary>,
  Simplify<SimpleTextSliceCenteredItem>
>;

/**
 * Slice variation for *SimpleText*
 */
type SimpleTextSliceVariation =
  | SimpleTextSliceDefault
  | SimpleTextSliceCentered;

/**
 * SimpleText Shared Slice
 *
 * - **API ID**: `simple_text`
 * - **Description**: SimpleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSlice = prismic.SharedSlice<
  "simple_text",
  SimpleTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterMenuDocument,
      FooterMenuDocumentData,
      FooterMenuDocumentDataMenuItemItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      SiteNavigationDocument,
      SiteNavigationDocumentData,
      SiteNavigationDocumentDataMenuItemItem,
      SiteNavigationDocumentDataCtaItemItem,
      AllDocumentTypes,
      BeforeAndAfterSlice,
      BeforeAndAfterSliceDefaultPrimary,
      BeforeAndAfterSliceVariation,
      BeforeAndAfterSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      SimpleTextSlice,
      SimpleTextSliceDefaultPrimary,
      SimpleTextSliceDefaultItem,
      SimpleTextSliceCenteredPrimary,
      SimpleTextSliceCenteredItem,
      SimpleTextSliceVariation,
      SimpleTextSliceDefault,
      SimpleTextSliceCentered,
    };
  }
}
