// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  before_and_after: dynamic(() => import("./BeforeAndAfter")),
  hero_section: dynamic(() => import("./HeroSection")),
  simple_text: dynamic(() => import("./SimpleText")),
};
