// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  simple_text: dynamic(() => import("./SimpleText")),
  hero_section: dynamic(() => import("./HeroSection")),
};
